# Generated by Django 5.1.3 on 2024-11-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.RemoveField(
            model_name='file',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='file',
            name='gcode_file',
            field=models.FileField(blank=True, null=True, upload_to='gcode/'),
        ),
        migrations.AddField(
            model_name='file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='file',
            name='printer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='stl_file',
            field=models.FileField(blank=True, null=True, upload_to='models/'),
        ),
    ]
