# Generated by Django 5.1.3 on 2024-11-20 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_file_file_remove_file_uploaded_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
